export const adminEndpoints = {
    verifyLogin : '/admin/verifyLogin',
    getUserData:'/admin/getUsers',
    getInstructorData:'/admin/getInstructor',
    createCategories:'/admin/createCategory',
    getCategoryData:'/admin/getCategory',
    editCategoryData:'/admin/editCategory',
    deleteCategoryData:'/admin/deleteCategory',
    blockUser:'/admin/blockUser',
    getInstructor:'/admin/getInstructorById',
    adminApprovel:'/admin/approveInstructor',
    cancelAdminApprovel:'/admin/cancelApprovel',
    getUser:'/admin/getUser',
    fetchDetails:'/admin/fetchDetails',
    fetchTransaction:'/admin/fetchTransaction' ,
    approveInstrcutors:'/admin/approveInstrcutors',
    monthlyRevenue:'/admin/revenue-summary',
    getTickets:'/admin/getTickets',
    updateTicket:'/admin/updateTicket',
    allInstructor:'/admin/allInstructor'
}