export const userEndpoints = {
    createUser : "/user/signup",
    verifyOtp : "/user/verifyOtp",
    verifyLogin : "/user/login",
    getCategory:'/user/home',
    getUserDetails:'/user/userDetails',
    editUserDetails:'/user/updateUser',
    getInstructorDetails:'/user/getInstructor',
    resendOtp:'/user/resendOtp',
    changePassword:'/user/changePassword',
    getInstructor:'/user/getInstructorData',
    payement:'/user/create-checkout-session',
    getSlots:'/user/getSlots',
    setImg:'/user/setImg',
    getImg:'/user/getImg',
    verifyRoom:'/user/verifyRoom',
    rating:'/user/rating',
    googleAuth:'/user/googleAuth',
    addReview:'/user/addReview',
    refreshToken:'/user/refreshToken',
    roomStatus:'/user/roomStatus',
    getTest:'/user/getTest',
    getQuestion:'/user/getQuestion',
    updateResult:'/user/updateResult',
    getCourse:'/user/getCourse',
    coursePayment:'/user/create-course-checkout-session',
    studentCourse:'/user/studentCourse',
    getNotification:'/user/getNotification',
    deleteNotifications:'/user/deleteNotifications',
    getBannerData:'/user/getBannerData',
    getLatesetCourse:'/user/latestCourse',
    getPopularInstructors:'/user/popularInstrcutors',
    getSearchCourse:'/user/searchCourse',
    raiseTicket:'/user/raiseTicket',
    createQnA:'/user/createQnA',
    fetchQnAData:'/user/fetchQnAData',
    announcements:'/user/announcements'
   
}